---
title: "p8105_hw5_jd3924"
author: "Jiahe Deng"
date: "2022-11-07"
output: github_document
---

```{r}
library(tidyverse)
```

```{r}
urlfile = "https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv"
homicides_data = read_csv(url(urlfile), na = c(" ", "Unknown"))
```
In this data, there is 52179 observations and 12 variables.
This data include each case's detailed information, such as victim's name(victim_first,victim_race), age(victim_age),gender(victim_sex), race(victim_race),location(city, state, lat, lon), the progress of the case(disposition), case's reported data(reported_date).
```{r}
homicides_data = 
  homicides_data %>%
  mutate(
    city_state = str_c(city,state, sep = ","),
    case_status = ifelse(disposition %in% c("Closed without arrest","Open/No arrest"), "unsolved","solved")
         ) %>% relocate(city_state) %>% 
  filter(city_state != "Tulsa,AL")
homicides_data
```
```{r}
homicides_data %>%
  group_by(city_state) %>%
  summarize(
    number_of_unsolved = sum(case_status=="unsolved"),
    number_of_homicides = n())
```
```{r}
baltimore_data = 
  homicides_data %>%
  filter(city_state == "Baltimore,MD")

baltimore_summary = 
  baltimore_data %>%
  summarise(
    unsolved_md = sum(case_status == "unsolved"),
    num = n())

prop.test(
  x = baltimore_summary %>% pull(unsolved_md),
  n = baltimore_summary %>% pull(num)
  ) %>%
  broom::tidy()
```
```{r}
prop_test = function(city){
  
  city_summary = 
    city %>% 
      summarise(
        unsolved = sum(case_status == 'unsolved'),
        n = n()
      )
  
  city_test = 
    prop.test(
      x = city_summary %>% pull(unsolved),
      n = city_summary %>% pull(n)
    )
  
  city_test
}
```
```{r} 
#use Baltimore to test whether the function works
prop_test(baltimore_data)
```

```{r}
statistic_df =
  homicides_data %>%
  nest(-city_state) %>%
  mutate(
    result = map(data, prop_test),
    tidy_data = map(result, broom::tidy)
  ) %>%
  select(city_state, tidy_data) %>%
  unnest(tidy_data) %>%
  select(city_state, estimate, starts_with("conf"))
statistic_df
```
```{r}
statistic_df %>%
  mutate(city_state = fct_reorder(city_state, estimate,.desc = TRUE)) %>%
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(
    title = "proportion of unsolved homicides",
    x = "location: city,state",
    y = "estimated proportion of unsolved homicides",
    caption = "Data from the Washington Post")
```



```{r}
#Conduct a hypothesis T test for n = 30, sigma = 5
sim_funct = function( 
    n = 30, 
    mu = 0,
    sigma = 5) {
  x = rnorm(n, mean = mu, sd = sigma)
  t_test = t.test(x, conf.int = 0.95) %>% broom::tidy()
  
  t_test
}
output = vector("list",5000) #Generate 5000 datasets for mu=0
for (i in 1: 5000) {
  output[[i]] = sim_funct()
}
output %>% bind_rows()
```

```{r}
#mu={1,2,3,4,5,6}
```

